import datetime

def create_changelog_page(changes):
    # Generate filename for the changelog page
    date = datetime.datetime.now().strftime('%Y-%m-%d')
    filename = f'changelog_{date}.html'

    # Create the HTML content for the changelog page
    content = f'''<!DOCTYPE html>
<html>
<head>
	<title>Changelog for {date}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style>
		body {{
			font-family: Arial, sans-serif;
			font-size: 16px;
			line-height: 1.5;
			color: #333;
		}}
		h1 {{
			font-size: 24px;
			font-weight: bold;
			margin-bottom: 20px;
		}}
		ul {{
			margin-top: 0;
			margin-bottom: 20px;
		}}
		li {{
			margin-bottom: 10px;
		}}
		.icon {{
			margin-right: 5px;
			font-size: 20px;
			vertical-align: middle;
		}}
		.added {{
			color: green;
		}}
		.changed {{
			color: blue;
		}}
		.removed {{
			color: red;
		}}
	</style>
</head>
<body>
	<h1>Changelog for {date}</h1>
	<ul>'''

    # Add each change to the HTML content
    for change in changes:
        icon = ''
        if change['type'] == 'added':
            icon = '<span class="icon added">&#x2714;</span>'
        elif change['type'] == 'changed':
            icon = '<span class="icon changed">&#x270E;</span>'
        elif change['type'] == 'removed':
            icon = '<span class="icon removed">&#x2718;</span>'
        content += f'<li>{icon}{change["message"]}</li>'

    # Add closing tags to the HTML content
    content += '''</ul>
	<script>
		// Automatically scroll to the bottom of the page on load
		window.onload = function() {
			window.scrollTo(0, document.body.scrollHeight);
		}
	</script>
</body>
</html>'''

    # Write the content to a file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

    # Return the filename
    return filename

import subprocess

# Get the Git log as a string
log = subprocess.check_output(['git', 'log', '--reverse', '--pretty=format:%s %ad', '--date=format:%Y-%m-%d']).decode('utf-8')

# Split the log string into a list of commit messages and timestamps
commits = log.split('\n')

# Create an HTML file
with open('wp-hooks-explorer/daily_changelog.html', 'w') as f:
    f.write(f'''<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Learn more about WordPress Hooks Explorer and its developer, Fahad Murtaza.">
    <meta property="og:title" content="Changelog - WordPress Hooks Explorer">
    <meta property="og:description" content="Changelog for WordPress Hooks Explorer- Autogenerated via git commits">
    <meta property="og:image" content="https://www.fahdmurtaza.com/wp-hooks-explorer/resources/images/wp-hook-explorer.jpg">
    <meta property="og:url" content="https://www.fahdmurtaza.com/wp-hooks-explorer/about.html">
    <meta name="twitter:title" content="Changelog - WordPress Hooks Explorer">
    <meta name="twitter:description" content="Changelog for WordPress Hooks Explorer - Learn about the frequent changes to WordPress Hooks Explorer developed by Fahad Murtaza">
    <meta name="twitter:image" content="https://www.fahdmurtaza.com/wp-hooks-explorer/resources/images/wp-hook-explorer.jpg">
    <meta name="twitter:card" content="summary_large_image">
    <title>Changelog - WordPress Hooks Explorer</title>
    <link rel="stylesheet" href="resources/css/bootstrap.min.css">
</head>
<body>
    <header class="bg-dark text-white text-center py-3">
        <h1> WordPress Hooks Explorer</h1>
        <p><a href="index.html" class="text-white">Back to home</a></p>
    </header>
    <main class="container mt-5 mb-5">
        <h1>Daily Changelog</h1>
            <ul>\n''')
    # Iterate through the commits and add each one to the HTML file
    for commit in commits:
        f.write(f'''                <li>{commit}</li>\n''')
    f.write(f'''
            </ul>''')
    f.write('''
        </main>

        <footer class="text-center footer mt-auto py-3 bg-light">
            <p>&copy; 2023 Fahad Murtaza aka iSuperCoder 2023.4.4</p>
        </footer>

        <script src="resources/js/jquery.min.js"></script>
        <script src="resources/js/bootstrap.bundle.min.js"></script>

    </body>
</html>''')
